<strong style="font-size : 30px; color:green">Numerical Python Library</strong>

In [ ]:
#NumPy = Numerical Python library for numerical computing.
'''
NumPy is an open-source Python library for numerical computing, 
provides a fast, memory-efficient N-dimensional array (ndarray) and 
a rich collection of mathematical, statistical, and linear algebra functions. 
It is optimized using C internally and forms the foundation of libraries such as Pandas, SciPy, and Scikit-learn.
'''

<strong style="font-size : 25px; color:green">Import Numpy</strong>

In [ ]:
#Import Statement - 
#NumPy - Numerical Python
import numpy as np #Import the NumPy library and use 'np' as its alias

<strong style="font-size : 25px; color:green">Create Arrays</strong>

In [ ]:
#create array using list
# Convert a Python list into a NumPy array
a = np.array([1,2,3,4,5,6]) 
print(a)

[1 2 3 4 5 6]


In [ ]:
#create array using tuple
# Convert a Python tuple into a NumPy array
a = np.array((1,2,3,4,5,6)) 
print(a)

[1 2 3 4 5 6]


In [ ]:
#2D Array
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<strong style="font-size : 25px; color:green">Array Properties</strong>

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)
'''
properties of Array
print(a.shape)       # Shape of the array (rows, columns)
print(a.ndim)        # Number of dimensions
print(a.size)        # Total number of elements
print(a.dtype)       # Data type of array elements
print(a.itemsize)    # Size of one element in bytes
print(a.nbytes)      # Total memory occupied by the array in bytes
#Special Arrays
# Zeros
print(np.zeros(5))          # Create a 1D array with 5 zeros
print(np.zeros((3,4)))      # Create a 3x4 array filled with zeros

#Ones
print(np.ones(5))           # Create a 1D array with 5 ones
print(np.ones((2,3)))       # Create a 2x3 array filled with ones

#Empty
print(np.empty((2,3)))      # Create a 2x3 array with uninitialized values

#Identity Matrix
print(np.eye(4))            # Create a 4x4 identity matrix

# Full
print(np.full((3,3),100))   # Create a 3x3 array filled with 100
'''


[[1 2 3]
 [4 5 6]]


In [14]:
#2D NumPy,Array properties
print("Row, Column =",arr.shape) # Shape of the array (rows, columns)

Row, Column = (2, 3)


In [ ]:
# Number of dimensions
print("Dimention of the given Array is :",arr.ndim) 

Dimention of the given Array is : 2


In [ ]:
# Total number of elements
print("Size of the Array is :",arr.size)  

Size of the Array is : 6


In [ ]:
# Data type of array elements
print("Data type of elements in Array is :",arr.dtype) 

Data type of elements in Array is : int64


In [ ]:
# Size of one element in bytes
print("Size of each Array element in Bytes is :",arr.itemsize,"bytes") 

Size of each Array element in Bytes is : 8 bytes


In [ ]:
# Total memory occupied by the array in bytes
print("Total size occupied by Array in memory is :",arr.nbytes,"bytes") 

Total size occupied by Array in memory is : 48 bytes


<strong style="font-size : 25px; color:green">Special Arrays</strong>

In [ ]:
#Special Arrays
# Create a 1D array with 5 zeros
print(np.zeros(5))  

[0. 0. 0. 0. 0.]


In [ ]:
# Create a 3x4 matrix filled with zeros
print(np.zeros((3,4))) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Create a 1D array with 5 ones
print(np.ones(5)) 

[1. 1. 1. 1. 1.]


In [ ]:
# Create a 2x3 matrix filled with ones
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
# Create a 2x3 array without initializing values 
# (Contains random values already present in memory)
print(np.empty((2,3))) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a 4x4 identity matrix  Diagonal elements = 1, others = 0
print(np.eye(4)) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Create a 3x3 matrix filled with the value 100
print(np.full((3,3),100)) 

[[100 100 100]
 [100 100 100]
 [100 100 100]]


<strong style="font-size : 25px; color:green">Create Number</strong>

In [ ]:
'''
# arange
print(np.arange(10))          # Create numbers from 0 to 9
print(np.arange(5,20))        # Create numbers from 5 to 19
print(np.arange(2,21,2))      # Create even numbers from 2 to 20
# linspace
print(np.linspace(0,100,11))  # Create 11 evenly spaced numbers from 0 to 100
# logspace
print(np.logspace(1,3,5))     # Create 5 logarithmically spaced numbers from 10¹ to 10³
'''

In [ ]:
# arange
# Create numbers from 0 to 9
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# Create numbers from 5 to 19
print(np.arange(5,20))        

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
# Create even numbers from 2 to 20
print(np.arange(2,21,2))      

[ 2  4  6  8 10 12 14 16 18 20]


In [60]:
# linspace
# Create 11 evenly spaced numbers from 5 to 100
print(np.linspace(5,100,11))  

[  5.   14.5  24.   33.5  43.   52.5  62.   71.5  81.   90.5 100. ]


In [ ]:
# logspace
# Create 5 logarithmically spaced numbers from 10¹ to 10³
print(np.logspace(1,2,5))    

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


<strong style="font-size : 25px; color:green">Random Number</strong>

In [ ]:
'''
print(np.random.rand(5))                    # Generate 5 random numbers between 0 and 1
print(np.random.randn(5))                   # Generate 5 random numbers from a normal distribution
print(np.random.randint(1,100,10))          # Generate 10 random integers from 1 to 99
print(np.random.random((3,4)))              # Generate a 3x4 array of random numbers between 0 and 1
print(np.random.choice([10,20,30,40],10))   # Randomly select 10 values from the given list
np.random.seed(10)                          # Set the random seed for reproducible results
print(np.random.randint(1,100,5))           # Generate the same random integers every time
'''

In [ ]:
 # Generate 5 random numbers between 0 and 1
print(np.random.rand(5))                 

[0.65810959 0.39176545 0.50698054 0.78032591 0.66003703]


In [73]:
 # Generate 5 random numbers from a normal distribution
print(np.random.randn(5))

[ 0.72280576 -0.7984818   1.7061397  -0.29744706 -0.24970972]


In [74]:
# Generate 10 random integers from 1 to 99
print(np.random.randint(1,100,10))          

[57 89 63 70 11  4 45  2 72 17]


In [75]:
# Generate a 3x4 array of random numbers between 0 and 1
print(np.random.random((3,4)))              

[[0.26129718 0.43651469 0.21134147 0.85831203]
 [0.02747653 0.20955752 0.48746651 0.22003407]
 [0.11698738 0.04413877 0.05244129 0.77794338]]


In [76]:
# Randomly select 10 values from the given list
print(np.random.choice([10,20,30,40],10))   

[40 30 40 10 20 10 40 30 20 20]


In [78]:
np.random.seed(10)                # Set the random seed for reproducible results
print(np.random.randint(1,100,5)) # Generate the same random integers every time

[10 16 65 29 90]


<strong style="font-size : 30px; color:green">Indexing</strong>

In [ ]:
# Create a 1D array
a = np.array([10,20,30,40,50])   
print("first element :",a[0])    # Access the first element

print("fourth element :",a[3])    # Access the fourth element

print("last element :",a[-1])   # Access the last element

print("second last element :",a[-2])   # Access the second last element

first element : 10
fourth element : 40
last element : 50
second last element : 40


In [ ]:
# Create a 3x3 array
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])      
# Access the first row        
print("first row :",a[0])

# Access the second row    
print("second row :",a[1])

 # Access the third row    
print("third row :",a[2]) 

# Access the element at row 2, column 3
print("element at row 2, column 3 :",a[1][2]) 

# Access the element at row 3, column 2
print("element at row 3, column 2 :",a[2][1]) 

# Access the element at row 2, column 3 (recommended syntax)
print("element at row 2, column 3",a[1,2])  

first row : [10 20 30]
second row : [40 50 60]
third row : [70 80 90]
element at row 2, column 3 : 60
element at row 3, column 2 : 80
element at row 2, column 3 60


<strong style="font-size : 30px; color:green">Slicing</strong>

In [ ]:
# 1D Array
# Create a 1D array
a = np.array([10,20,30,40,50,60,70]) 

# Access all elements
print("all elements :",a[:])   

# Access elements from index 2 to the end   
print("elements from index 2 to the end :",a[2:]) 

# Access elements from the beginning to index 4    
print("elements from the beginning to index 4 :",a[:5]) 

 # Access elements from index 2 to index 5  
print("from index 2 to index 5 :",a[2:6])   

# Access every second element
print("every second element :",a[::2]) 

# Reverse the array   
print("Reverse order :",a[::-1])   

all elements : [10 20 30 40 50 60 70]
elements from index 2 to the end : [30 40 50 60 70]
elements from the beginning to index 4 : [10 20 30 40 50]
from index 2 to index 5 : [30 40 50 60]
every second element : [10 30 50 70]
Reverse order : [70 60 50 40 30 20 10]


In [84]:
# 2D Array
# Create a 3x3 array
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])                
 # Access the second column
print("second column :",a[:,1])  

 # Access the second row
print("second row :",a[1,:]) 

# Access rows 1-2 and columns 2-3    
print("rows 1-2 and columns 2-3 :",a[0:2,1:3])  

second column : [20 50 80]
second row : [40 50 60]
rows 1-2 and columns 2-3 : [[20 30]
 [50 60]]


<strong style="font-size : 30px; color:green">Reshape</strong>

In [ ]:
a = np.arange(12)        # Create an array with values from 0 to 11

print(a.reshape(3,4))    # Reshape into a 3x4 array
print(a.reshape(2,6))    # Reshape into a 2x6 array
print(a.reshape(4,3))    # Reshape into a 4x3 array

<strong style="font-size : 30px; color:green">Flatten</strong>

In [85]:
 # Create a 2x3 array
a = np.array([
    [1,2,3],
    [4,5,6]
])                    
 # Convert the array into a new 1D array (creates a copy)
print(a.flatten())  
 # Convert the array into a 1D array (returns a view when possible)  
print(a.ravel())      

[1 2 3 4 5 6]
[1 2 3 4 5 6]
