<strong style="font-size : 30px; color:green">Numerical Python Library</strong>

In [ ]:
#NumPy = Numerical Python library for numerical computing.
'''
NumPy is an open-source Python library for numerical computing, 
provides a fast, memory-efficient N-dimensional array (ndarray) and 
a rich collection of mathematical, statistical, and linear algebra functions. 
It is optimized using C internally and forms the foundation of libraries such as Pandas, SciPy, and Scikit-learn.
'''

<strong style="font-size : 25px; color:green">Import Numpy</strong>

In [2]:
#Import Statement - 
#NumPy - Numerical Python
import numpy as np #Import the NumPy library and use 'np' as its alias

<strong style="font-size : 25px; color:green">Create Arrays</strong>

In [ ]:
#create array using list
# Convert a Python list into a NumPy array
a = np.array([1,2,3,4,5,6]) 
print(a)

[1 2 3 4 5 6]


In [ ]:
#create array using tuple
# Convert a Python tuple into a NumPy array
a = np.array((1,2,3,4,5,6)) 
print(a)

[1 2 3 4 5 6]


In [ ]:
#2D Array
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<strong style="font-size : 25px; color:green">Array Properties</strong>

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)
'''
properties of Array
print(a.shape)       # Shape of the array (rows, columns)
print(a.ndim)        # Number of dimensions
print(a.size)        # Total number of elements
print(a.dtype)       # Data type of array elements
print(a.itemsize)    # Size of one element in bytes
print(a.nbytes)      # Total memory occupied by the array in bytes
#Special Arrays
# Zeros
print(np.zeros(5))          # Create a 1D array with 5 zeros
print(np.zeros((3,4)))      # Create a 3x4 array filled with zeros

#Ones
print(np.ones(5))           # Create a 1D array with 5 ones
print(np.ones((2,3)))       # Create a 2x3 array filled with ones

#Empty
print(np.empty((2,3)))      # Create a 2x3 array with uninitialized values

#Identity Matrix
print(np.eye(4))            # Create a 4x4 identity matrix

# Full
print(np.full((3,3),100))   # Create a 3x3 array filled with 100
'''


[[1 2 3]
 [4 5 6]]


In [14]:
#2D NumPy,Array properties
print("Row, Column =",arr.shape) # Shape of the array (rows, columns)

Row, Column = (2, 3)


In [ ]:
# Number of dimensions
print("Dimention of the given Array is :",arr.ndim) 

Dimention of the given Array is : 2


In [ ]:
# Total number of elements
print("Size of the Array is :",arr.size)  

Size of the Array is : 6


In [ ]:
# Data type of array elements
print("Data type of elements in Array is :",arr.dtype) 

Data type of elements in Array is : int64


In [ ]:
# Size of one element in bytes
print("Size of each Array element in Bytes is :",arr.itemsize,"bytes") 

Size of each Array element in Bytes is : 8 bytes


In [ ]:
# Total memory occupied by the array in bytes
print("Total size occupied by Array in memory is :",arr.nbytes,"bytes") 

Total size occupied by Array in memory is : 48 bytes


<strong style="font-size : 25px; color:green">Special Arrays</strong>

In [ ]:
#Special Arrays
# Create a 1D array with 5 zeros
print(np.zeros(5))  

[0. 0. 0. 0. 0.]


In [ ]:
# Create a 3x4 matrix filled with zeros
print(np.zeros((3,4))) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Create a 1D array with 5 ones
print(np.ones(5)) 

[1. 1. 1. 1. 1.]


In [ ]:
# Create a 2x3 matrix filled with ones
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
# Create a 2x3 array without initializing values 
# (Contains random values already present in memory)
print(np.empty((2,3))) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a 4x4 identity matrix  Diagonal elements = 1, others = 0
print(np.eye(4)) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Create a 3x3 matrix filled with the value 100
print(np.full((3,3),100)) 

[[100 100 100]
 [100 100 100]
 [100 100 100]]


<strong style="font-size : 25px; color:green">Create Number</strong>

In [ ]:
'''
# arange
print(np.arange(10))          # Create numbers from 0 to 9
print(np.arange(5,20))        # Create numbers from 5 to 19
print(np.arange(2,21,2))      # Create even numbers from 2 to 20
# linspace
print(np.linspace(0,100,11))  # Create 11 evenly spaced numbers from 0 to 100
# logspace
print(np.logspace(1,3,5))     # Create 5 logarithmically spaced numbers from 10¹ to 10³
'''

In [ ]:
# arange
# Create numbers from 0 to 9
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# Create numbers from 5 to 19
print(np.arange(5,20))        

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
# Create even numbers from 2 to 20
print(np.arange(2,21,2))      

[ 2  4  6  8 10 12 14 16 18 20]


In [60]:
# linspace
# Create 11 evenly spaced numbers from 5 to 100
print(np.linspace(5,100,11))  

[  5.   14.5  24.   33.5  43.   52.5  62.   71.5  81.   90.5 100. ]


In [ ]:
# logspace
# Create 5 logarithmically spaced numbers from 10¹ to 10³
print(np.logspace(1,2,5))    

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


<strong style="font-size : 25px; color:green">Random Number</strong>

In [ ]:
'''
print(np.random.rand(5))                    # Generate 5 random numbers between 0 and 1
print(np.random.randn(5))                   # Generate 5 random numbers from a normal distribution
print(np.random.randint(1,100,10))          # Generate 10 random integers from 1 to 99
print(np.random.random((3,4)))              # Generate a 3x4 array of random numbers between 0 and 1
print(np.random.choice([10,20,30,40],10))   # Randomly select 10 values from the given list
np.random.seed(10)                          # Set the random seed for reproducible results
print(np.random.randint(1,100,5))           # Generate the same random integers every time
'''

In [ ]:
 # Generate 5 random numbers between 0 and 1
print(np.random.rand(5))                 

[0.65810959 0.39176545 0.50698054 0.78032591 0.66003703]


In [73]:
 # Generate 5 random numbers from a normal distribution
print(np.random.randn(5))

[ 0.72280576 -0.7984818   1.7061397  -0.29744706 -0.24970972]


In [74]:
# Generate 10 random integers from 1 to 99
print(np.random.randint(1,100,10))          

[57 89 63 70 11  4 45  2 72 17]


In [75]:
# Generate a 3x4 array of random numbers between 0 and 1
print(np.random.random((3,4)))              

[[0.26129718 0.43651469 0.21134147 0.85831203]
 [0.02747653 0.20955752 0.48746651 0.22003407]
 [0.11698738 0.04413877 0.05244129 0.77794338]]


In [76]:
# Randomly select 10 values from the given list
print(np.random.choice([10,20,30,40],10))   

[40 30 40 10 20 10 40 30 20 20]


In [78]:
np.random.seed(10)                # Set the random seed for reproducible results
print(np.random.randint(1,100,5)) # Generate the same random integers every time

[10 16 65 29 90]


<strong style="font-size : 25px; color:green">Indexing</strong>

In [ ]:
# Create a 1D array
a = np.array([10,20,30,40,50])   
print("first element :",a[0])    # Access the first element

print("fourth element :",a[3])    # Access the fourth element

print("last element :",a[-1])   # Access the last element

print("second last element :",a[-2])   # Access the second last element

first element : 10
fourth element : 40
last element : 50
second last element : 40


In [ ]:
# Create a 3x3 array
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])      
# Access the first row        
print("first row :",a[0])

# Access the second row    
print("second row :",a[1])

 # Access the third row    
print("third row :",a[2]) 

# Access the element at row 2, column 3
print("element at row 2, column 3 :",a[1][2]) 

# Access the element at row 3, column 2
print("element at row 3, column 2 :",a[2][1]) 

# Access the element at row 2, column 3 (recommended syntax)
print("element at row 2, column 3",a[1,2])  

first row : [10 20 30]
second row : [40 50 60]
third row : [70 80 90]
element at row 2, column 3 : 60
element at row 3, column 2 : 80
element at row 2, column 3 60


<strong style="font-size : 25px; color:green">Slicing</strong>

In [ ]:
# 1D Array
# Create a 1D array
a = np.array([10,20,30,40,50,60,70]) 

# Access all elements
print("all elements :",a[:])   

# Access elements from index 2 to the end   
print("elements from index 2 to the end :",a[2:]) 

# Access elements from the beginning to index 4    
print("elements from the beginning to index 4 :",a[:5]) 

 # Access elements from index 2 to index 5  
print("from index 2 to index 5 :",a[2:6])   

# Access every second element
print("every second element :",a[::2]) 

# Reverse the array   
print("Reverse order :",a[::-1])   

all elements : [10 20 30 40 50 60 70]
elements from index 2 to the end : [30 40 50 60 70]
elements from the beginning to index 4 : [10 20 30 40 50]
from index 2 to index 5 : [30 40 50 60]
every second element : [10 30 50 70]
Reverse order : [70 60 50 40 30 20 10]


In [84]:
# 2D Array
# Create a 3x3 array
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])                
 # Access the second column
print("second column :",a[:,1])  

 # Access the second row
print("second row :",a[1,:]) 

# Access rows 1-2 and columns 2-3    
print("rows 1-2 and columns 2-3 :",a[0:2,1:3])  

second column : [20 50 80]
second row : [40 50 60]
rows 1-2 and columns 2-3 : [[20 30]
 [50 60]]


<strong style="font-size : 25px; color:green">Reshape</strong>

In [ ]:
a = np.arange(12)        # Create an array with values from 0 to 11

print(a.reshape(3,4))    # Reshape into a 3x4 array
print(a.reshape(2,6))    # Reshape into a 2x6 array
print(a.reshape(4,3))    # Reshape into a 4x3 array

<strong style="font-size : 25px; color:green">Flatten</strong>

In [85]:
 # Create a 2x3 array
a = np.array([
    [1,2,3],
    [4,5,6]
])                    
 # Convert the array into a new 1D array (creates a copy)
print(a.flatten())  
 # Convert the array into a 1D array (returns a view when possible)  
print(a.ravel())      

[1 2 3 4 5 6]
[1 2 3 4 5 6]


<strong style="font-size : 25px; color:green">Transpose</strong>

In [4]:
# Create a 2x3 array
a = np.array([
    [1,2,3],
    [4,5,6]
])                    
# Transpose the array (rows become columns and columns become rows)
print("Original Array")
print(a)
print("Tranpose")
print(a.T)             

Original Array
[[1 2 3]
 [4 5 6]]
Tranpose
[[1 4]
 [2 5]
 [3 6]]


<strong style="font-size : 25px; color:green">Arithmetic</strong>

In [ ]:
a = np.array([10,20,30])    # Create the first array
b = np.array([1,2,3])       # Create the second array

print(a + b)    # Add corresponding elements
print(a - b)    # Subtract corresponding elements
print(a * b)    # Multiply corresponding elements
print(a / b)    # Divide corresponding elements
print(a // b)   # Perform floor division on corresponding elements
print(a % b)    # Find the remainder of corresponding elements
print(a ** 2)   # Square each element of array 'a'

<strong style="font-size : 25px; color:green">Universal Functions</strong>

In [ ]:
# Create a NumPy array
a = np.array([4,9,16,25])   

print(np.sqrt(a))     # Calculate the square root of each element
print(np.square(a))   # Calculate the square of each element
print(np.exp(a))      # Calculate e raised to the power of each element
print(np.log(a))      # Calculate the natural logarithm (base e) of each element
print(np.sin(a))      # Calculate the sine of each element (in radians)
print(np.cos(a))      # Calculate the cosine of each element (in radians)
print(np.tan(a))      # Calculate the tangent of each element (in radians)

[2. 3. 4. 5.]
[ 16  81 256 625]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
[1.38629436 2.19722458 2.77258872 3.21887582]
[-0.7568025   0.41211849 -0.28790332 -0.13235175]
[-0.65364362 -0.91113026 -0.95765948  0.99120281]
[ 1.15782128 -0.45231566  0.30063224 -0.13352641]


<strong style="font-size : 25px; color:green">Statistics</strong>

In [8]:
 # Create a NumPy array
a = np.array([10,20,30,40,50])  

print(np.sum(a))      # Calculate the sum of all elements
print(np.mean(a))     # Calculate the average (mean) of the elements
print(np.median(a))   # Calculate the median (middle value)
print(np.max(a))      # Find the maximum element
print(np.min(a))      # Find the minimum element
print(np.std(a))      # Calculate the standard deviation
print(np.var(a))      # Calculate the variance
print(np.prod(a))     # Calculate the product of all elements

150
30.0
30.0
50
10
14.142135623730951
200.0
12000000


<strong style="font-size : 25px; color:green">Axis Operations</strong>

In [ ]:
# Create a 2D NumPy array
a = np.array([
    [10,20,30],
    [40,50,60]
])                        

print(np.sum(a))          # Calculate the sum of all elements
print(np.sum(a,axis=0))   # Calculate the column-wise sum
print(np.sum(a,axis=1))   # Calculate the row-wise sum
print(np.mean(a,axis=0))  # Calculate the column-wise average
print(np.mean(a,axis=1))  # Calculate the row-wise average

210
[50 70 90]
[ 60 150]
[25. 35. 45.]
[20. 50.]


<strong style="font-size : 25px; color:green">Sorting</strong>

In [9]:
# Create a 1D NumPy array
a = np.array([50,20,80,10,60])   
 # Sort the array in ascending order
print(np.sort(a))               

# 2D Array
# Create a 2D NumPy array
a = np.array([
    [9,2,4],
    [8,5,1]
])                               
# Sort each row in ascending order
print(np.sort(a))                

[10 20 50 60 80]
[[2 4 9]
 [1 5 8]]


<strong style="font-size : 25px; color:green">Searching</strong>

In [10]:
# Create a NumPy array
a = np.array([10,20,30,40,30])   
# Find the indices where the value is 30
print(np.where(a == 30))    
# Find the indices where the value is greater than 20     
print(np.where(a > 20))          

(array([2, 4]),)
(array([2, 3, 4]),)


<strong style="font-size : 25px; color:green">Filtering</strong>

In [11]:
 # Create a NumPy array
a = np.array([10,20,30,40,50])  
# Filter and display elements greater than 20
print(a[a > 20])    
 # Filter and display elements divisible by 20            
print(a[a % 20 == 0])          

[30 40 50]
[20 40]


<strong style="font-size : 25px; color:green">Unique</strong>

In [12]:
# Create a NumPy array with duplicate values
a = np.array([1,2,2,3,3,3,4])   
 # Return only unique values from the array
print(np.unique(a))             

[1 2 3 4]


<strong style="font-size : 25px; color:green"> Insert Delete Append</strong>

In [13]:
# Create a NumPy array
a = np.array([10,20,30])      
# Add an element at the end of the array
print(np.append(a,40))  
# Insert 100 at index position 1      
print(np.insert(a,1,100)) 
# Delete the element at index position 1    
print(np.delete(a,1))         

[10 20 30 40]
[ 10 100  20  30]
[10 30]


<strong style="font-size : 25px; color:green">Concatenate</strong>

In [ ]:
# Create the first array
a = np.array([1,2,3])
# Create the second array          
b = np.array([4,5,6])          
# Join two arrays into a single array
print(np.concatenate((a,b)))  

[1 2 3 4 5 6]


<strong style="font-size : 25px; color:green">Stack</strong>

In [18]:
# Stack arrays vertically (row-wise)
print(np.vstack((a,b)),"\n")  
# Stack arrays horizontally (column-wise)   
print(np.hstack((a,b)),"\n")  
# Stack arrays depth-wise (third dimension)   
print(np.dstack((a,b)),"\n")     

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[[[1 4]
  [2 5]
  [3 6]]] 



<strong style="font-size : 25px; color:green">Split</strong>

In [ ]:
# Create an array with values from 0 to 11
a = np.arange(12)            
# Split the array into 3 equal parts
print(np.split(a,3))         

<strong style="font-size : 25px; color:green">Copy vs View</strong>

In [19]:
# Create an original array
a = np.array([1,2,3])        
# Create a separate copy of the array
b = a.copy()                 
# Create a view sharing the same memory
c = a.view()                 
# Modify the first element of original array
a[0] = 100                   
# Display original array
print(a)                    
# Display copied array (unchanged)
print(b)    
# Display view array (changed)                 
print(c)                     

[100   2   3]
[1 2 3]
[100   2   3]


<strong style="font-size : 25px; color:green">Boolean Operations</strong>

In [20]:
# Create a NumPy array
a = np.array([10,20,30,40,50])  
# Check which elements are greater than 25
print(a > 25)                   
# Filter elements greater than 25
print(a[a > 25])                

[False False  True  True  True]
[30 40 50]


<strong style="font-size : 25px; color:green">Broadcasting</strong>

In [21]:
# Create a 2D array
a = np.array([
    [1,2,3],
    [4,5,6]
])                              
# Add a scalar value to every element
print(a + 10)                   
# Create a 1D array
b = np.array([100,200,300])    
# Add array values using broadcasting
print(a + b)                   

[[11 12 13]
 [14 15 16]]
[[101 202 303]
 [104 205 306]]


<strong style="font-size : 25px; color:green">Matrix Multiplication</strong>

In [22]:
# Create first matrix
a = np.array([
    [1,2],
    [3,4]
])                              
# Create second matrix
b = np.array([
    [5,6],
    [7,8]
])                              
# Perform matrix multiplication using @ operator
print(a @ b)                    
# Perform matrix multiplication using dot function
print(np.dot(a,b))              

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


<strong style="font-size : 25px; color:green">Linear Algebra</strong>

In [28]:
# Create a square matrix
a= np.array([
    [1,2],
    [3,4]
])                         
# Calculate the determinant of the matrix
print("Determinant :",np.linalg.det(a),"\n")     
# Calculate the inverse of the matrix
print("Leverage :",np.linalg.inv(a),"\n")     
# Calculate eigenvalues and eigenvectors of the matrix
print("Eigenvalues and Eigenvector :",np.linalg.eig(a))     

Determinant : -2.0000000000000004 

Leverage : [[-2.   1. ]
 [ 1.5 -0.5]] 

Eigenvalues and Eigenvector : EigResult(eigenvalues=array([-0.37228132+0.j,  5.37228132+0.j]), eigenvectors=array([[-0.82456484+0.j, -0.41597356+0.j],
       [ 0.56576746+0.j, -0.90937671+0.j]]))


<strong style="font-size : 25px; color:green">Save & Load</strong>

In [29]:
# Create a NumPy array
a = np.array([10,20,30])    
# Save the array into a .npy file
np.save("data.npy",a)       
# Load the saved array from the file
b = np.load("data.npy")     
# Display the loaded array
print(b)                    

[10 20 30]


<strong style="font-size : 25px; color:green">Helpful Functions</strong>

In [30]:
a  = np.arange(12)           # Create an array with values from 0 to 11

print(a.reshape(3,4))       # Reshape array into 3 rows and 4 columns

print(a.reshape(-1,2))      # Automatically calculate rows with 2 columns

print(a.reshape(2,-1))      # Automatically calculate columns with 2 rows

print(a.argmax())           # Find the index position of maximum value

print(a.argmin())           # Find the index position of minimum value

print(np.clip(a,3,8))       # Limit values between minimum 3 and maximum 8

print(np.round(3.14159,2))  # Round value to 2 decimal places

print(np.ceil(3.2))         # Round value upward to the next integer

print(np.floor(3.9))        # Round value downward to the previous integer

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
11
0
[3 3 3 3 4 5 6 7 8 8 8 8]
3.14
4.0
3.0


<strong style="font-size : 25px; color:green">Advanced Indexing</strong>

In [31]:
a  = np.array([10,20,30,40,50])   # Create a 1D array

print(a[[0,2,4]])                # Access multiple elements using index list

a = np.arange(16).reshape(4,4)   # Create a 4x4 matrix

print(a[[0,2],[1,3]])            # Access elements using row and column index pairs

[10 30 50]
[ 1 11]


<strong style="font-size : 25px; color:green">Fancy Indexing</strong>

In [32]:
a = np.arange(20)                # Create an array from 0 to 19

index = [1,5,9,12]               # Create a list of required index positions

print(a[index])                  # Extract elements using multiple indices

[ 1  5  9 12]
